name: Deploy React app to Azure Static Web Apps

on:
  push:
    branches: ["main"] # trigger on main
  pull_request:
    branches: ["main"] # preview URLs for PRs

env:
  APP_LOCATION: "/" # where package.json lives
  OUTPUT_LOCATION: "dist" # CRA/Vite default output
  NODE_VERSION: "20" # or 20 if you prefer

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1 # pin to a release if you like
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOPTEX_API_TOKEN }}
          action: upload
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
